# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ByoMachineTemplate
metadata:
  name: 493e77a7-md-normal
  namespace: 493e77a7
spec:
  template:
    spec:
      selector:
        matchLabels:
          role: worker
