# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: 493e77a7-md-taco
  namespace: 493e77a7
spec:
  template:
    spec: {}
